### ISSUE TITLE
無顯示表單

### ISSUE THREAD

**Issue by hsuan1117** [TFcis/SkyOnlinejudge#73]
許多表單的格子都沒有顯示出來

![Screenshot_20191112_120020](https://user-images.githubusercontent.com/34859514/68640905-1109ee80-0544-11ea-9f8f-2c21d1e17d3c.jpg)
![Screenshot_20191112_120013](https://user-images.githubusercontent.com/34859514/68640907-1109ee80-0544-11ea-8e2e-4f303b2466e9.jpg)

**Comment by lys0829** [comment]
用電腦試試，然後trace一下error XD
