### ISSUE TITLE
Remove Account

### ISSUE THREAD

**Issue by davidhcefx** [TFcis/SkyOnlinejudge#76]
我希望能夠刪除我自己的帳號。

根據個資法第 3 條：
```
第 3 條  當事人就其個人資料依本法規定行使之下列權利，不得預先拋棄或以特約限制之：
    一、查詢或請求閱覽。
    二、請求製給複製本。
    三、請求補充或更正。
    四、請求停止蒐集、處理或利用。
    五、請求刪除。
```

然而，帳號名稱不僅會出現於 Google search result 當中，還不能變更或刪除。
再加上，很多課程助教規定，帳號名稱必須為 `學號 + 姓名` 的形式，才會計入課程成績當中。
舉例來說，[這個頁面](https://pc2.tfcis.org/sky/index.php/chal/list/375)，搜尋 "104" 就會發現很多這樣的例子。
上述狀況，對於個資在在都是種侵害。
因此本人在此提出帳號刪除或修改名稱的支援。

**Comment by lys0829** [comment]
不好意思，請您提供帳號以便我們處理，謝謝

**Comment by LFsWang** [comment]
You can edit your nickname (it will change your name shown on website) on sky.tfcis.org on Account page now. However, if you want to remove account, you need to provide more information to verify your relation between account.
